# Name of the GitHub Actions workflow
name: ETL CI/CD Pipeline

# Defines the events that trigger the workflow
on:
    push:
        branches: [main] # Runs on pushes to the main branch
    pull_request:
        branches: [main] # Runs on pull requests targeting the main branch
   
# Defines the jobs to be executed
jobs:
    test:
        runs-on: ubuntu-latest # Specifies the runner environment (latest Ubuntu)
        steps:
        # Step 1: Checks out the repository code
        - name: Checkout code
          uses: actions/checkout@v3 # Uses the checkout action version 3

        # Step 2: Sets up Python environment
        - name: Set up Python
          uses: actions/setup-python@v4 # Uses the setup-python action version 4
          with:
            python-version: '3.11' # Specifies the Python version to use

        # Step 3: Installs dependencies
        - name: Install dependencies
          run: pip install -r requirements.txt # Installs dependencies from requirements.txt

        # Step 4: Runs unit tests
        - name: Run tests
          run: pytest tests/  # Executes pytest on the tests directory

    # Job for deploying AWS Step Function
    deploy-step-function:
        # This job runs only on pushes to the main branch
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest 
        needs: test # This job depends on the completion of the 'test' job
        steps:
        # Step 1: Checks out the repository code
        - name: Checkout code
          uses: actions/checkout@v3 # Uses the checkout action version 3
        # Step 2: Deploys or updates AWS Step Function state machine
        - name: Deploy State Machine
          run: |
            aws stepfunctions update-state-machine \
             --state-machine-arn arn:aws:states:us-east-1:<ACCOUNT_ID>:stateMachine:LakehouseOrchestrator \
             --definition file://step_functions/state_machine.json
          env:
            # Environment variables for AWS authentication and configuration
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key from GitHub secrets
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret key from GitHub secrets
            AWS_REGION: eu-north-1  # Specifies AWS region for deployment


